name: Alpha Workflow
 
on:
  push:
    branches:
      - main  # Or any branch you want to trigger the workflow on
 
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
 
      - name: Run build
        run: |
          echo "Building the project..."
 
      - name: Deploy
        run: |
          echo "Deploying the project..."
